#%RAML 1.0 DataType

type: object
displayName: user
properties:
  id:
    type: number
  userName:
    type: string
  firstName:
    type: string
  lastName:
    type: string
  enabled:
    type: boolean
